// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ final class ListenerRecord {


    /*package*/ final TextboxListener mListener;

    public ListenerRecord(
            @CheckForNull TextboxListener listener) {
        this.mListener = listener;
    }

    @CheckForNull
    public TextboxListener getListener() {
        return mListener;
    }

    @Override
    public String toString() {
        return "ListenerRecord{" +
                "mListener=" + mListener +
        "}";
    }

}
