// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ final class SortRecord {


    /*package*/ final SortItems mSorter;

    public SortRecord(
            @CheckForNull SortItems sorter) {
        this.mSorter = sorter;
    }

    @CheckForNull
    public SortItems getSorter() {
        return mSorter;
    }

    @Override
    public String toString() {
        return "SortRecord{" +
                "mSorter=" + mSorter +
        "}";
    }

}
