// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "sort_record.hpp"

namespace djinni_generated {

class NativeSortRecord final {
public:
    using CppType = ::textsort::SortRecord;
    using JniType = jobject;

    using Boxed = NativeSortRecord;

    ~NativeSortRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSortRecord();
    friend ::djinni::JniClass<NativeSortRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/textsort/SortRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lcom/dropbox/textsort/SortItems;)V") };
    const jfieldID field_mSorter { ::djinni::jniGetFieldID(clazz.get(), "mSorter", "Lcom/dropbox/textsort/SortItems;") };
};

} // namespace djinni_generated
