// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "listener_record.hpp"

namespace djinni_generated {

class NativeListenerRecord final {
public:
    using CppType = ::textsort::ListenerRecord;
    using JniType = jobject;

    using Boxed = NativeListenerRecord;

    ~NativeListenerRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeListenerRecord();
    friend ::djinni::JniClass<NativeListenerRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/textsort/ListenerRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lcom/dropbox/textsort/TextboxListener;)V") };
    const jfieldID field_mListener { ::djinni::jniGetFieldID(clazz.get(), "mListener", "Lcom/dropbox/textsort/TextboxListener;") };
};

} // namespace djinni_generated
