// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeSortRecord.hpp"  // my header
#include "NativeSortItems.hpp"

namespace djinni_generated {

NativeSortRecord::NativeSortRecord() = default;

NativeSortRecord::~NativeSortRecord() = default;

auto NativeSortRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSortRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeSortItems::fromCpp(jniEnv, c.sorter)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSortRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSortRecord>::get();
    return {::djinni_generated::NativeSortItems::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mSorter))};
}

} // namespace djinni_generated
