// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeListenerRecord.hpp"  // my header
#include "NativeTextboxListener.hpp"

namespace djinni_generated {

NativeListenerRecord::NativeListenerRecord() = default;

NativeListenerRecord::~NativeListenerRecord() = default;

auto NativeListenerRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeListenerRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeTextboxListener::fromCpp(jniEnv, c.listener)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeListenerRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeListenerRecord>::get();
    return {::djinni_generated::NativeTextboxListener::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mListener))};
}

} // namespace djinni_generated
