// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include <memory>
#include <utility>

namespace textsort {

class TextboxListener;

struct ListenerRecord final {
    /*not-null*/ std::shared_ptr<TextboxListener> listener;

    //NOLINTNEXTLINE(google-explicit-constructor)
    ListenerRecord(/*not-null*/ std::shared_ptr<TextboxListener> listener_)
    : listener(std::move(listener_))
    {}
};

} // namespace textsort
