// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include <memory>
#include <utility>

namespace textsort {

class SortItems;

struct SortRecord final {
    /*not-null*/ std::shared_ptr<SortItems> sorter;

    //NOLINTNEXTLINE(google-explicit-constructor)
    SortRecord(/*not-null*/ std::shared_ptr<SortItems> sorter_)
    : sorter(std::move(sorter_))
    {}
};

} // namespace textsort
