// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

namespace textsort {

enum class sort_order;
struct ItemList;
struct ListenerRecord;
struct SortRecord;

class SortItems {
public:
    virtual ~SortItems() = default;

    /** For the iOS / Android demo */
    virtual void sort(sort_order order, const ItemList & items) = 0;

    static SortRecord create_with_listener(const ListenerRecord & listener);

    /** For the localhost / command-line demo */
    static ItemList run_sort(const ItemList & items);
};

} // namespace textsort
