// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import <Foundation/Foundation.h>
@protocol TXSTextboxListener;

@interface TXSListenerRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithListener:(nullable id<TXSTextboxListener>)listener NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)listenerRecordWithListener:(nullable id<TXSTextboxListener>)listener;

@property (nonatomic, readonly, nullable) id<TXSTextboxListener> listener;

@end
