// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSListenerRecord.h"
#include "listener_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSListenerRecord;

namespace djinni_generated {

struct ListenerRecord
{
    using CppType = ::textsort::ListenerRecord;
    using ObjcType = TXSListenerRecord*;

    using Boxed = ListenerRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
