// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSListenerRecord.h"


@implementation TXSListenerRecord

- (nonnull instancetype)initWithListener:(nullable id<TXSTextboxListener>)listener
{
    if (self = [super init]) {
        _listener = listener;
    }
    return self;
}

+ (nonnull instancetype)listenerRecordWithListener:(nullable id<TXSTextboxListener>)listener
{
    return [[self alloc] initWithListener:listener];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p listener:%@>", self.class, (void *)self, self.listener];
}

#endif
@end
