// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSListenerRecord+Private.h"
#import "TXSTextboxListener+Private.h"
#include <cassert>

namespace djinni_generated {

auto ListenerRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni_generated::TextboxListener::toCpp(obj.listener)};
}

auto ListenerRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSListenerRecord alloc] initWithListener:(::djinni_generated::TextboxListener::fromCpp(cpp.listener))];
}

} // namespace djinni_generated
