// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSItemList.h"
#import "TXSListenerRecord.h"
#import "TXSSortOrder.h"
#import "TXSSortRecord.h"
#import <Foundation/Foundation.h>


@interface TXSSortItems : NSObject

/** For the iOS / Android demo */
- (void)sort:(TXSSortOrder)order
       items:(nonnull TXSItemList *)items;

+ (nonnull TXSSortRecord *)createWithListener:(nonnull TXSListenerRecord *)listener;

/** For the localhost / command-line demo */
+ (nonnull TXSItemList *)runSort:(nonnull TXSItemList *)items;

@end
