// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSSortRecord+Private.h"
#import "TXSSortItems+Private.h"
#include <cassert>

namespace djinni_generated {

auto SortRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni_generated::SortItems::toCpp(obj.sorter)};
}

auto SortRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSSortRecord alloc] initWithSorter:(::djinni_generated::SortItems::fromCpp(cpp.sorter))];
}

} // namespace djinni_generated
