// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import <Foundation/Foundation.h>
@class TXSSortItems;

@interface TXSSortRecord : NSObject
- (nonnull instancetype)init NS_UNAVAILABLE;
+ (nonnull instancetype)new NS_UNAVAILABLE;
- (nonnull instancetype)initWithSorter:(nullable TXSSortItems *)sorter NS_DESIGNATED_INITIALIZER;
+ (nonnull instancetype)sortRecordWithSorter:(nullable TXSSortItems *)sorter;

@property (nonatomic, readonly, nullable) TXSSortItems * sorter;

@end
