// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSSortRecord.h"
#include "sort_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSSortRecord;

namespace djinni_generated {

struct SortRecord
{
    using CppType = ::textsort::SortRecord;
    using ObjcType = TXSSortRecord*;

    using Boxed = SortRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
