// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#import "TXSSortRecord.h"


@implementation TXSSortRecord

- (nonnull instancetype)initWithSorter:(nullable TXSSortItems *)sorter
{
    if (self = [super init]) {
        _sorter = sorter;
    }
    return self;
}

+ (nonnull instancetype)sortRecordWithSorter:(nullable TXSSortItems *)sorter
{
    return [[self alloc] initWithSorter:sorter];
}

#ifndef DJINNI_DISABLE_DESCRIPTION_METHODS
- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p sorter:%@>", self.class, (void *)self, self.sorter];
}

#endif
@end
