// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "listener_record.hpp"

namespace djinni_generated {

struct NativeListenerRecord
{
    using CppType = ::textsort::ListenerRecord;
    using JsType = em::val;
    using Boxed = NativeListenerRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
