// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeSortRecord.hpp"  // my header
#include "NativeSortItems.hpp"

namespace djinni_generated {

auto NativeSortRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni_generated::NativeSortItems::Boxed::toCpp(j["sorter"])};
}
auto NativeSortRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("sorter", ::djinni_generated::NativeSortItems::Boxed::fromCpp(c.sorter));
    return js;
}

} // namespace djinni_generated
