// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from example.djinni

#include "NativeListenerRecord.hpp"  // my header
#include "NativeTextboxListener.hpp"

namespace djinni_generated {

auto NativeListenerRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni_generated::NativeTextboxListener::Boxed::toCpp(j["listener"])};
}
auto NativeListenerRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("listener", ::djinni_generated::NativeTextboxListener::Boxed::fromCpp(c.listener));
    return js;
}

} // namespace djinni_generated
